### ISSUE TITLE
Event Calendar

### ISSUE THREAD

**Issue by Toddsand21** [ONRR/onrr.gov-site#545] opened 2021-03-02 17:29 UTC
Nageezi, Huerfano, and Bloomfield, NM Area Meeting 
Meeting will be held for IIM Account Holders, Indian mineral owners and Indian Trust property owners by telephone..
Wednesday, March 10, 2021 from 1:30 pm to 3:00 pm   Call-In Number: (888) 455-7033   Pass Code: 2637410
Topics Presented  •	FIMO ONRR & BIA: O&G updates  • Navajo Regional BIA Probate:  Death Reporting Process and checking n status of probates  • BTFA Eastern Navajo Area FTO:  BTFA updates   • Public Q&A session following updates.  • Individual Q&A's.   Representatives from BTFA (formerly OST IIM), BIA Navajo Regional Probate and Estates Services, and Federal Indian Minerals Office (FIMO – Navajo allotted oil and gas leasing and royalties) will be present to answer questions.  If you would like to discuss any of your issues with someone from FIMO, please call our toll-free number at 1 (800) 238-2839, Monday-Friday from 7:30 am- 4:30 pm.  Please have any documents you want to discuss available

KAULEY MEETING 
Wednesday, March 17, 2021 from 1:00 pm to 2:00 pm
Meeting will be held for IIM account holders, Indian mineral owners and other trust property owners in the Southern Plains Region in Oklahoma by telephone..   Call-in Number: (866) 778-1299    Passcode:  5826518 
For those who plan to attend please call the ONRR Office at (800) 354-7015 prior to the meeting to reserve your space for this meeting.  A limited number of lines will be open for callers for this meeting.  Topics Presented:  • ONRR Updates and calendar year-end statistics   • BTFA - Anadarko Agency (formerly OST)  • BLM – OK representatives  • BIA - Southern Plains Region OK 
•  Individual Q&A session after presentations.  If you would like to discuss any of your issues with someone from ONRR OKC Office, please call our toll-free number at (800) 354-7015, Monday-Friday from 7:30 am – 5:00 pm.   Please have any documents you want to discuss available.

Ft Berthold and Bismarck, North Dakota Area Meeting 
Wednesday, March 24, 2021 from 1:00 pm -2:00 pm 
The meeting will be held for IIM account holders, Indian mineral owners and other trust property owners in the Ft Berthold and Bismarck, ND areas by telephone.  Representatives from the four agencies including the Bureau of Land Management (BLM), Bureau of Trust Funds Administration (BTFA), the Bureau of Indian Affairs (BIA), and the Office of Natural Resources Revenue (ONRR) will be available to ask questions during the meeting.  For more information and to sign up to attend the meeting please contact the ONRR Denver Outreach Office at (800) 982-3226.

**Comment by lpgoldstein** [comment] 2021-03-02 20:23
@Toddsand21 Can you please send the link for where you want this to be posted?

**Comment by Toddsand21** [comment] 2021-03-02 20:54
It's under the Event Calendar at this onnr.gov site:    https://www.onrr.gov/IndianServices/index.htm#

**Comment by lpgoldstein** [comment] 2021-03-03 21:09
@Toddsand21 This is ready for your review. Some of the data fields are empty but we are unable to remove them from the code until we redo the site. Please let me know what we should add. http://2017onrr/IndianServices/index.htm#

**Comment by Toddsand21** [comment] 2021-03-04 16:25
Can I first ask if you can delete some items that are no longer needed on the webpage?  They are on the Allottee Assistance page after clicking on the Indian Services tab.  On the very right hand side of the page you'll see the tab "Event Calendar."  That is where my updated events will be placed.  But at the moment there are events from April 2020 that can all be deleted first.  I am proofreading them now and will let you know when they are ready to be added to that same "Event Calendar" tab.  But could you delete those first?

**Comment by lpgoldstein** [comment] 2021-03-04 16:31
Please clear your cache to view: http://2017onrr/IndianServices/index.htm#
The old events have been deleted

**Comment by Toddsand21** [comment] 2021-03-04 20:27
Are you talking about the fields like "Location" and City, State?  We might can come up for something to put in those fields.  What about the size you have everything.  I would like to make the Title in large print. as in the name of the meeting in LARGE PRINT of Larger Print and make Event Contact smaller.  The way it is now It looks like that the Event Contact is more important than who we are meeting with,  i.e. KAULEY MEETING.

**Comment by lpgoldstein** [comment] 2021-03-04 22:12
@Toddsand21 let me check with a developer. I'm not sure if we can change that in a timely fashion- we are literally making changes through an excel type format that was set up by whoever set up this feature of the website.

**Comment by Toddsand21** [comment] 2021-03-04 23:25
Ok that's fine, I'll wait to hear on that.  Can we use bullets for any part of our announcement?

Sandra Todd
Minerals Revenue Specialist
Office of Natural Resources Revenue
Indian Outreach, OKC
(405) 879-6052
(800) 354-7015
________________________________

**Comment by lpgoldstein** [comment] 2021-03-05 00:25
@toddsand21 - make sure you clear your cache/browsing history again and then check out what we have live now https://www.onrr.gov/IndianServices/index.htm# I wanted to make sure that we get the meeting info up in a timely fashion and then we can always make more changes.

**Comment by Toddsand21** [comment] 2021-03-09 17:10
On the Location:  Part of each one of these could we put in "By Telephone" to make sure the customer knows these meetings are by telephone only?    2) And can we delete some of the information we have there on one of the meetings?  And I guess there was no way to adjust the size of Title of the meeting?

**Comment by Toddsand21** [comment] 2021-03-09 18:03
I don't remember signing off on the Event Calendar as ready to go on our last conversation.  There are several items that are wrong on all 3 events listed.  Can you make these changes immediately?  1) on Nageezi Meeting for FIMO at the end change the Event Contact: Email to: leona.begay@onrr.gov.   2) On the Kauley Meeting under the Event Contact info change the Phone number to: (800) 354-7015.  and 3) change the Email: to onrroutreachokc@onrr.gov.  And 4) on Ft Berthold Meeting change the Event contact Phone to: (800) 982-3226 and 5) and Change the Email to: onrroutreachdenver@onrr.gov.  We need these done asap.

**Comment by Maroyafaied** [comment] 2021-03-09 21:50
@Toddsand21 since @lpgoldstein is not working this week, I went ahead and made the changes you requested in the dev site. Please let me know if everything looks correct on the dev site to publish. 

http://2017onrr/IndianServices/index.htm#

Thanks

**Comment by Toddsand21** [comment] 2021-03-09 22:59
For some reason I can't see the updates.  I'm signing off here for today.  I'll try and get to it 1st thing in the morning.  Thx.

**Comment by Maroyafaied** [comment] 2021-03-09 23:10
@Toddsand21 try clearing your cache by pressing ctrl and F5 together.

**Comment by Toddsand21** [comment] 2021-03-10 15:41
Yes that looks fine with me and fine to update. So is there a box to check or some way to confirm that "yes this final is now ready" to be uploaded to the actual page?  Because I don't remember doing that last week before it was done.  I was aware of the first meeting date was close but I rather have all the information correct before we put it out there. Plus, I am a first-time user of this software.  Thank you!

**Comment by Maroyafaied** [comment] 2021-03-10 15:48
@Toddsand21 there is not a box, we just ask that you confirm in the comments in the GitHub issue. @lpgoldstein made it live since she didn't hear back and she's planning on taking leave for a while so she made it live since it seemed urgent.  We apologize it wasn't correct and in the future, we won't make the changes live unless you confirm it's correct. I'll go ahead and make the changes live since you confirmed, it should be live on the site in about 30 minutes. Thanks!

**Comment by Maroyafaied** [comment] 2021-03-10 16:31
@Toddsand21 the changes are on the live site. I will close this issue. Thanks

**Comment by Toddsand21** [comment] 2021-03-10 16:31
That's great.  I am sure it'll all help with our 3 offices.  Sorry I had to take off Friday which was urgent and unplanned and I couldn't back to you until yesterday.  But it all looks great and I appreciate all of your help.  .

**Closed by Maroyafaied** 2021-03-10 16:31 UTC
Labels: maintenance
