### ISSUE TITLE
Linking documents bugs

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/onrr.gov-site#1731] opened 2022-03-17 19:08 UTC
Hi Mojo,

I'm trying to relink documents and am running into the following issues on the Anti-Harassment page (https://dev-onrr-cms.app.cloud.gov/admin/content/pages/32)

In the 'ONRR Response' section, I'm trying to relink and when I search for the document in the inline link function, I'm seeing duplicates. There are no duplicates of these files in the pdf folder or the CMS webpage.
![image.png](https://images.zenhubusercontent.com/60f9807ebc2bf779cc3921f2/f61324dd-c0a7-4c4d-b753-945bb3165e3a)
![image.png](https://images.zenhubusercontent.com/60f9807ebc2bf779cc3921f2/d67be9bd-e141-4e3d-be96-b6512fa89205)
![image.png](https://images.zenhubusercontent.com/60f9807ebc2bf779cc3921f2/20856bbc-978e-4d74-8f5d-bd0a1ce73abf)

It's hit-or-miss if the pdf icon will display:

![image.png](https://images.zenhubusercontent.com/60f9807ebc2bf779cc3921f2/7823db83-950a-4111-a33f-844c0baff5a3)

When I select the first file link option, the url isn't updated, but the PDF will display:
![image.png](https://images.zenhubusercontent.com/60f9807ebc2bf779cc3921f2/730a62f4-33a2-4804-8852-ecafb26a5deb)

When I select the second file link option, the URLs are corrected, but the PDFs won't display:
![image.png](https://images.zenhubusercontent.com/60f9807ebc2bf779cc3921f2/681d80f3-25a2-4b84-ba95-621849ade8be)

**Comment by mcharg** [comment] 2022-03-17 19:18
@mojobnichols I'm not seeing duplicates, but @Maroyafaied is.  Could it be a permissions thing?

**Comment by mojobnichols** [comment] 2022-03-17 19:32
It appears that something is still generating
 he old url.   Which is causing the duplicate and hit or miss on PDF displaying.   Please refrain from updating the urls untill I figure out the cause. 


update the new trigger was not installed correctly in dev and it was generating the url in the old way causing the duplicates.  I will remove the duplicates.

**Comment by cthomasONRR** [comment] 2022-03-17 19:43
@mojobnichols YAY! I was able to properly relink, corrected url and pdfs are all displaying.

In the CMS, I don't see any formatting issues to correct: 
![image](https://user-images.githubusercontent.com/72526208/158882917-4bb3653d-b74c-45c3-acd4-8628429b3663.png)

But the webpage is displaying the pdf icons irregularly, and now there's an odd space in the list:
![image](https://user-images.githubusercontent.com/72526208/158883025-391070aa-4d4e-4953-b6ec-129d57bf6d3d.png)

**Comment by mcharg** [comment] 2022-03-21 18:44
Closing, since we haven't encountered any new bugs.

**Closed by mcharg** 2022-03-21 18:44 UTC
Labels: bug, P3: Medium, CMS
